### ISSUE TITLE
`totalLQTYTokensStaked` in the subgraph returns incorrect amount

### ISSUE THREAD

**Issue by danielattilasimon** [liquity/dev#556]
For example at the time of this writing, only about 1.84M LQTY is staked, but the subgraph returns 3.16M.

**Comment by danielattilasimon** [comment]
Ah, here's the problem:
https://github.com/liquity/dev/blob/44033a0edb09a6c4790c157a37b055136fcc63d5/packages/subgraph/src/entities/Global.ts#L148-L161

`amountChange` is negative in the case of unstaking, but we subtract it anyway.

**Comment by edmulraney** [comment]
Oh! I thought it was a positive number. Great catch. I'll fix that now

**Comment by edmulraney** [comment]
Resolved by:
