### ISSUE TITLE
Do brownie tests work?

### ISSUE THREAD

**Issue by AlanVerbner** [liquity/dev#595]
# Description

I'm trying to execute the brownie tests as described [here](https://github.com/liquity/dev#brownie-tests) and it seems it's throwing an error due to a missing parameter. Once I add it I get a different error.

```bash
        # LQTY
        contracts.lqtyStaking = LQTYStaking.deploy({ 'from': accounts[0] })
        contracts.communityIssuance = CommunityIssuance.deploy({ 'from': accounts[0] })
        contracts.lockupContractFactory = LockupContractFactory.deploy({ 'from': accounts[0] })
>       contracts.lqtyToken = LQTYToken.deploy(
            contracts.communityIssuance.address,
            contracts.lqtyStaking.address,
            contracts.lockupContractFactory.address,
            accounts[0], # bountyAddress
            accounts[0],  # lpRewardsAddress
            { 'from': accounts[0] }
        )
E       ValueError: constructor Sequence has incorrect length, expected 6 but got 5
```
## Expected bahavior

To execute `brownie test -s` and get a successful execution.

**Comment by bingen** [comment]
Hey @AlanVerbner thanks for raising this!
PR #598 should fix it. Can you confirm?

**Comment by AlanVerbner** [comment]
Hi @bingen thanks for the quick response! It's working now although it seems it doesn't finish. I'll dig into the code to check what actually those tests do but at least it seems to be ok now! :smile:

**Comment by bingen** [comment]
Ok, cool! Yes, it takes really long. These are not common tests actually, it’s a port of some economic simulations we had in Python, that we wanted to check using real contracts, so we used Brownie. Our regular unit tests are done using hardhat, in `test` folder.

**Comment by AlanVerbner** [comment]
Thanks @bingen !
