### ISSUE TITLE
possible to give an option to borrow from a list of tokens, instead of just LUSD token.

### ISSUE THREAD

**Issue by sajwanAshish** [liquity/dev#633]
can we give users a option to borrow from a list of tokens instead of just LUSD tokens..  ?

@danielattilasimon @RickGriff

**Comment by RickGriff** [comment]
Hi Sajwan - as stated in the docs, Liquity is immutable and cannot be altered post-deployment.  What you're suggesting sounds like a huge change and a very different protocol :)
