### ISSUE TITLE
Suggestion (secrets.js)

### ISSUE THREAD

**Issue by Rjrunner44** [liquity/dev#645]
add secrets.js to gitignore (for those who create one so it's not accidentally pushed).

**Comment by bingen** [comment]
Which package do you mean? For contracts it’s here:
https://github.com/liquity/dev/blob/main/packages/contracts/.gitignore#L18

**Comment by Rjrunner44** [comment]
ah, yes. I see it. please close. For some reason I missed the .gitignore in this dir...
