### ISSUE TITLE
Proxy.sol failing compile b/c of a different Solidity version

### ISSUE THREAD

**Issue by willvlad** [liquity/dev#681]
Any idea how to solve this issue when compiling the contracts? Proxy.sol breaks the compile/migrate flow because of its earlier version and I'm not sure how to solve it:

```
liquity/packages/contracts/contracts/TestContracts/DappSys/proxy.sol:23:1: ParserError: Source file requires different compiler version (current compiler is 0.6.11+commit.5ef660b1.Emscripten.clang) - note that nightly builds are considered to be strictly less than the released version
pragma solidity ^0.4.23;
^----------------------^

Error: Truffle is currently using solc 0.6.11, but one or more of your contracts specify "pragma solidity ^0.4.23".
Please update your truffle config or pragma statement(s).
(See https://trufflesuite.com/docs/truffle/reference/configuration#compiler-configuration for information on
configuring Truffle to use a specific solc compiler version.)
```

**Comment by bingen** [comment]
Hey @willvlad how are you compiling? If you use `npx hardhat compile` it works fine.
Our hardhat config file already has that solidity version included:
https://github.com/liquity/dev/blob/main/packages/contracts/hardhat.config.js#L37

**Comment by bingen** [comment]
Hey @willvlad I’m closing this issue, let me know if you need further assistance or feel free to re-open it if that solution doesn’t work for you. Thanks.

**Comment by 7770x** [comment]
Yes, that's fine with hardhat. I was confused because you also have a truffle config there. By the way, where do you guys switch the pricefeed from test to external source? I've tried putting pricefeedtest = false, but it's still showing test prices
