### ISSUE TITLE
Latest updates break deploys

### ISSUE THREAD

**Issue by willvlad** [liquity/dev#695]
Might be the bump-up of the ethers or hardhat version, but something is breaking deploys in the latest repo version. 

To reproduce, just yarn the current verion of the repo and try to deploy the contract locally or to testnet and you'll see the following error:

```
yarn run v1.22.11
$ yarn workspace @liquity/lib-ethers hardhat deploy --network localhost
$ hardhat deploy --network localhost
An unexpected error occurred:

hardhat.config.ts:147:18 - error TS2339: Property 'ethers' does not exist on type 'HardhatRuntimeEnvironment'.

147       return env.ethers.getContractFactory(abi, bytecode, signer);
                     ~~~~~~
hardhat.config.ts:149:16 - error TS2339: Property 'ethers' does not exist on type 'HardhatRuntimeEnvironment'.

149   : env => env.ethers.getContractFactory;
                   ~~~~~~
hardhat.config.ts:198:36 - error TS2339: Property 'ethers' does not exist on type 'HardhatRuntimeEnvironment'.

198       const [deployer] = await env.ethers.getSigners();
                                       ~~~~~~

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
```

**Comment by danielattilasimon** [comment]
Good spot! I fixed this in #693 after seeing your comment in that other PR. Can you try with latest main?

**Comment by willvlad** [comment]
Great, working now! 

By the way, can one update the PriceFeed to Chainlink's feed on rinkeby rather than the hardcoded test one?

**Comment by danielattilasimon** [comment]
Yes, add the following parameter to the deploy command to use a real pricefeed:
```
yarn deploy --network rinkeby --use-real-price-feed true
```

**Comment by danielattilasimon** [comment]
Fixed by #693

**Comment by willvlad** [comment]
> Yes, add the following parameter to the deploy command to use a real pricefeed:
> 
> ```
> yarn deploy --network rinkeby --use-real-price-feed true
> ```

Thanks @danielattilasimon. Where can one find a list of all params like that?

**Comment by danielattilasimon** [comment]
You can list all params with
```
yarn deploy --help
```

**Comment by willvlad** [comment]
> Yes, add the following parameter to the deploy command to use a real pricefeed:
> 
> ```
> yarn deploy --network rinkeby --use-real-price-feed true
> ```

@danielattilasimon Tried deploying with this flag, it's breaking at the PriceFeed stage for some reason:

```

Error: cannot estimate gas; transaction may fail or may require manual gas limit (error={"name":"ProviderError","code":3,"_isProviderError":true,"data"....

....
reason: 'cannot estimate gas; transaction may fail or may require manual gas limit',
  code: 'UNPREDICTABLE_GAS_LIMIT',
  error: ProviderError: execution reverted: PriceFeed: Chainlink must be working and current

```
easy to repro - just run yarn and then your command above...

**Comment by danielattilasimon** [comment]
That happens from time to time. Chainlink on Rinkeby is unreliable and there are periods where the price is frozen for extended periods. The Liquity PriceFeed can only be deployed at a time when there's been a Chainlink price update within the last 4 hours.

We chose this timeout because Chainlink promises to update the price at least once every hour, but it seems that's only guaranteed on mainnet.

You should retry at a different time.

**Comment by willvlad** [comment]
Thanks @danielattilasimon. A quick question - going through your repo, I noticed you have rinkebyDeployment.js and mainnetDeployment.js as well as deploymentParams.rinkeby and mainnet in the contracts folder amongst other deploy scripts. How are they different to the deploy.ts script in the lib-ethers/utils folder? There are also very many hard-coded addresses in the former files. Is the deploy.ts file what you guys use to deploy or some other script because these two sets of scripts don't seem to be interacting between each other.
